
spring.application.name=vehicle-rental

spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_rental
spring.datasource.username=root
spring.datasource.password=Hema@@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true